#ifndef REGS_SYSTIMER_H
#define REGS_SYSTIMER_H

#include <stdint.h>

#define SYSTEM_BASE_ADDRESS 0x600C0000
#define SYSTIMER_BASE_ADDRESS 0x60023000

#define SYSTEM_PERIP_CLK_EN0_REG (*(volatile uint32_t *)(SYSTEM_BASE_ADDRESS + 0x0010))

#define SYSTIMER_CONF_REG (*(volatile uint32_t *)(SYSTIMER_BASE_ADDRESS))
#define SYSTIMER_TIMER_TARGET0_LO_REG (*(volatile uint32_t *)(SYSTIMER_BASE_ADDRESS + 0x001C)) 
#define SYSTIMER_TIMER_TARGET0_HI_REG (*(volatile uint32_t *)(SYSTIMER_BASE_ADDRESS + 0x0020))
#define SYSTIMER_TARGET0_CONF_REG (*(volatile uint32_t *)(SYSTIMER_BASE_ADDRESS + 0x0034))
#define SYSTIMER_UNIT0_OP_REG (*(volatile uint32_t *)(SYSTIMER_BASE_ADDRESS + 0x0004))
#define SYSTIMER_COMP0_LOAD_REG (*(volatile uint32_t *)(SYSTIMER_BASE_ADDRESS + 0x0050))
#define SYSTIMER_INT_ENA_REG (*(volatile uint32_t *)(SYSTIMER_BASE_ADDRESS + 0x0064))


#define SYSTEM_SYSTIMER_CLK_EN (1U << 29)

#define SYSTIMER_TIMER_UNIT0_UPDATE (1U << 30)
#define SYSTIMER_TIMER_UNIT0_WORK_EN (1U << 30)
#define SYSTIMER_TIMER_UNIT0_CORE0_STALL_EN (1U << 28)
#define SYSTIMER_TARGET0_WORK_EN (1U << 24)

#define SYSTIMER_TARGET0_PERIOD_MODE (1U << 30)
 
#endif
